language: minimal

services: docker

node_js: 12

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.29.2

before_install:
  - echo 'docker-compose installed and configured'
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo 'dockerhub credentials configured'

script:
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-restapi-feed ifahadashraf/udagram-restapi-feed:v1
  - docker tag udagram-restapi-user ifahadashraf/udagram-restapi-user:v1
  - docker tag udagram-frontend ifahadashraf/udagram-frontend:v1
  - docker tag reverseproxy ifahadashraf/reverseproxy:v1
  - docker push ifahadashraf/udagram-restapi-feed
  - docker push ifahadashraf/udagram-restapi-user
  - docker push ifahadashraf/udagram-frontend
  - docker push ifahadashraf/reverseproxy
      